### ISSUE TITLE
v2ray一键安装脚本的问题

### ISSUE THREAD

**Issue by hydrogenisdru** [abcfyk/impatriot#2]
服务端全部都装好了，客户端的config文件使用脚本导出的config.json.client作为config.json放在v2Ray目录中，然后打开v2RayN.exe，模式选择的http代理-》PAC模式，这样对吗？目前的现象是，配置里面一个配置好的服务器都看不到，而且也翻不了墙0 - 0

**Comment by hydrogenisdru** [comment]
已解决。

**Comment by ummmme** [comment]
所有的GUI客户端，建议都自己根据脚本生成的config.json.client文件，手动填写相关的参数，
其实无非就是 客户端信息（唯一ID，alterID，服务器地址，端口），协议信息（路径，域名）
